dist: xenial
language: python
python:
  - 3.7

services:
  - docker

before_install:
  - docker swarm init
  - git clone https://github.com/openfaas/faas
  - cd faas
  - ./deploy_stack.sh
  - curl -sL https://cli.openfaas.com | sudo sh
  - git clone https://github.com/afcyber-dream/piedpiper-flake8-faas
  - cd piedpiper-flake8-validator
  - faas build && faas deploy
