dist: xenial
language: python
python:
  - 3.7

services:
  - docker

before_install:
  - bash <(curl -s https://raw.githubusercontent.com/afcyber-dream/ansible-collection-pidev/master/bootstrap.sh) afcyber-dream/ansible-collection-pidev ubuntu1804/dockerswarm+openfaas
